import json
from datetime import datetime, timedelta
import requests


def load_last_punch_time():
    """Load last punch time from JSON file"""
    try:
        with open('last_punch_time.json', 'r', encoding='utf-8') as f:
            return json.load(f)
    except:
        return {"att_date": "01-01-2000", "punch_time": "00:00", "emp_code": ""}


def save_last_punch_time(att_date, punch_time, emp_code):
    """Save the most recent punch time to JSON"""
    data = {"att_date": att_date, "punch_time": punch_time, "emp_code": emp_code}
    with open('last_punch_time.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
    print(f"Updated last punch time: {att_date} {punch_time} - {emp_code}")


def process_new_records(data):
    """Process and filter new records"""
    last_punch = load_last_punch_time()
    print(
        f"Last punch time: {last_punch['att_date']} {last_punch['punch_time']} - {last_punch.get('emp_code', '')}")

    new_records = []
    latest_datetime = None
    latest_record = None

    # Tạo datetime thực tế của last_punch để so sánh
    last_punch_datetime = datetime.strptime(f"{last_punch['att_date']} {last_punch['punch_time']}", "%d-%m-%Y %H:%M")

    for record in data['data']:
        record_datetime = datetime.strptime(f"{record['att_date']} {record['punch_time']}", "%d-%m-%Y %H:%M")

        # So sánh trực tiếp với datetime thực tế của last_punch
        if record_datetime > last_punch_datetime:
            new_records.append(record)

            if latest_datetime is None or record_datetime > latest_datetime:
                latest_datetime = record_datetime
                latest_record = record
        elif record_datetime == last_punch_datetime:
            # Kiểm tra duplicate cho cùng datetime
            if record['emp_code'] == last_punch.get('emp_code', ''):
                print(f"Skipping duplicate: {record['emp_code']} - {record['att_date']} {record['punch_time']}")
                continue
            else:
                # Cùng thời gian nhưng khác nhân viên - vẫn là record mới
                new_records.append(record)

                if latest_datetime is None or record_datetime > latest_datetime:
                    latest_datetime = record_datetime
                    latest_record = record

    # call_api(new_records)

    if latest_record:
        save_last_punch_time(latest_record['att_date'], latest_record['punch_time'], latest_record['emp_code'])

    print_result(new_records)


def call_api(new_records):
    url = "http://171.244.133.113:3293/api/cham_cong_van_tay_v2/"
    headers = {'Content-Type': 'application/json'}
    device_name = 'DPS2'

    for row in new_records:
        try:
            att_date = row['att_date']
            punch_time = row['punch_time']
            timestamp = datetime.strptime(f"{att_date} {punch_time}", "%d-%m-%Y %H:%M").strftime(
                "%Y-%m-%d %H:%M:%S")
            payload = {'msnv': row['emp_code'], 'kihieumay': device_name, 'timestamp': timestamp}

            res = requests.post(url, headers=headers, json=payload)
            if res.status_code != 200:
                print(f"Error {res.status_code}: {res.text}")
                break
        except Exception as e:
            print(f"Exception on row {row['id']}: {e}")
            break


def print_result(new_records):
    print(f"Found {len(new_records)} new records:")
    for i, record in enumerate(new_records, 1):
        print(
            f"{i}. {record['first_name']} ({record['emp_code']}) - {record['att_date']} {record['punch_time']} - {record['punch_state']}")


data = {
    "count": 47,
    "next": None,
    "previous": None,
    "msg": "",
    "code": 0,
    "data": [
        {
            "id": 488,
            "emp_code": "143009",
            "first_name": "Trần Quốc Hưng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 510,
            "emp_code": "143009",
            "first_name": "Trần Quốc Hưng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:45",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 526,
            "emp_code": "143009",
            "first_name": "Trần Quốc Hưng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 484,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:54",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 499,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:11",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 500,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:11",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 506,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 524,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 528,
            "emp_code": "150006",
            "first_name": "Trần Lê Bảo Nhi",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:18",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 525,
            "emp_code": "153008",
            "first_name": "Lê Hoài Nam",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 489,
            "emp_code": "153014",
            "first_name": "Nguyễn Văn Huy2",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 516,
            "emp_code": "153014",
            "first_name": "Nguyễn Văn Huy2",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 517,
            "emp_code": "153014",
            "first_name": "Nguyễn Văn Huy2",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:43",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 486,
            "emp_code": "153027",
            "first_name": "Nguyễn Đắc Quang",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 503,
            "emp_code": "153027",
            "first_name": "Nguyễn Đắc Quang",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:04",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 487,
            "emp_code": "153033",
            "first_name": "Trần Quốc Toản",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 507,
            "emp_code": "153033",
            "first_name": "Trần Quốc Toản",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:22",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 483,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:53",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 496,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 497,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 504,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 505,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 519,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:53",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 498,
            "emp_code": "163016",
            "first_name": "Phạm Thế Sơn",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:10",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 502,
            "emp_code": "163016",
            "first_name": "Phạm Thế Sơn",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 527,
            "emp_code": "163016",
            "first_name": "Phạm Thế Sơn",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:07",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 485,
            "emp_code": "163028",
            "first_name": "Nguyễn Thành Vỹ",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 511,
            "emp_code": "163028",
            "first_name": "Nguyễn Thành Vỹ",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 520,
            "emp_code": "163028",
            "first_name": "Nguyễn Thành Vỹ",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:55",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 492,
            "emp_code": "163046",
            "first_name": "Lê Đình Tuyến",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 512,
            "emp_code": "163046",
            "first_name": "Lê Đình Tuyến",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 523,
            "emp_code": "163046",
            "first_name": "Lê Đình Tuyến",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 490,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 491,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 493,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:04",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 494,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:04",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 495,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:04",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 514,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 515,
            "emp_code": "173016",
            "first_name": "Nguyễn Kim Hải Đă",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 513,
            "emp_code": "173019",
            "first_name": "Đinh Văn Lộc",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:46",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 521,
            "emp_code": "173019",
            "first_name": "Đinh Văn Lộc",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:55",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 482,
            "emp_code": "173031",
            "first_name": "Trần Nguyễn Hoàng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:44",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 508,
            "emp_code": "173031",
            "first_name": "Trần Nguyễn Hoàng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:32",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 518,
            "emp_code": "173031",
            "first_name": "Trần Nguyễn Hoàng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:43",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 501,
            "emp_code": "173042",
            "first_name": "Lâm Thùy Tâm",
            "last_name": None,
            "nick_name": "",
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "09:41",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 509,
            "emp_code": "173042",
            "first_name": "Lâm Thùy Tâm",
            "last_name": None,
            "nick_name": "",
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "06-08-2025",
            "work_code_alias": "0",
            "punch_time": "17:34",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 522,
            "emp_code": "173042",
            "first_name": "Lâm Thùy Tâm",
            "last_name": None,
            "nick_name": "",
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:59",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        }
    ]
}

data_one_day = {
    "count": 12,
    "next": None,
    "previous": None,
    "msg": "",
    "code": 0,
    "data": [
        {
            "id": 526,
            "emp_code": "143009",
            "first_name": "Trần Quốc Hưng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:05",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 524,
            "emp_code": "143012",
            "first_name": "Phạm Huỳnh Long",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 528,
            "emp_code": "150006",
            "first_name": "Trần Lê Bảo Nhi",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:18",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 525,
            "emp_code": "153008",
            "first_name": "Lê Hoài Nam",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:03",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 517,
            "emp_code": "153014",
            "first_name": "Nguyễn Văn Huy2",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:43",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 519,
            "emp_code": "163015",
            "first_name": "Cao Nguyễn Anh Thiên",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:53",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 527,
            "emp_code": "163016",
            "first_name": "Phạm Thế Sơn",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:07",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 520,
            "emp_code": "163028",
            "first_name": "Nguyễn Thành Vỹ",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:55",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 523,
            "emp_code": "163046",
            "first_name": "Lê Đình Tuyến",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "08:02",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 521,
            "emp_code": "173019",
            "first_name": "Đinh Văn Lộc",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:55",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 518,
            "emp_code": "173031",
            "first_name": "Trần Nguyễn Hoàng",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:43",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        },
        {
            "id": 522,
            "emp_code": "173042",
            "first_name": "Lâm Thùy Tâm",
            "last_name": None,
            "nick_name": "",
            "gender": None,
            "dept_code": "1",
            "dept_name": "CC",
            "company_code": "1",
            "company_name": "company.default",
            "position_code": None,
            "position_name": None,
            "work_code": "0",
            "att_date": "07-08-2025",
            "work_code_alias": "0",
            "punch_time": "07:59",
            "punch_state": "Check Out",
            "verify_type": "Fingerprint",
            "source": "Device"
        }
    ]
}

print(process_new_records(data))
