import json
from datetime import datetime, timedelta


def load_last_punch_time():
    """Load last punch date from JSON file"""
    try:
        with open('last_punch_time.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('last_date', '2025-01-01')
    except:
        return '2025-01-01'


def load_last_record():
    """Load last record date from JSON file"""
    try:
        with open('last_records.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('data', '')
    except:
        return ''


def save_last_date(date_str):
    """Save the most recent date to JSON"""
    data = {"last_date": date_str}
    with open('last_punch_time.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
    print(f"\nUpdated last processed date: {date_str}")


def save_last_record(records):
    data = {"data": records}
    with open('last_records.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
    print(f"\nUpdated last records.")


def call_api(new_records):
    url = "http://171.244.133.113:3293/api/cham_cong_van_tay_v2/"
    headers = {'Content-Type': 'application/json'}
    device_name = 'HCM'

    for row in new_records:
        # try:
        att_date = row['att_date']
        clock_in = row['clock_in']
        clock_out = row['clock_out']

        timestamp_clockin = datetime.strptime(f"{att_date} {clock_in}", "%Y-%m-%d %H:%M").strftime(
            "%Y-%m-%d %H:%M:%S")
        timestamp_clockout = datetime.strptime(f"{att_date} {clock_out}", "%Y-%m-%d %H:%M").strftime(
            "%Y-%m-%d %H:%M:%S")

        # Fix: Remove unnecessary loop and use the correct timestamp variable
        # Assuming you want to send both clock in and clock out records

        # Payload for clock in
        payload_in = {'msnv': row['emp_code'], 'kihieumay': device_name, 'timestamp': timestamp_clockin}
        print("call call (clock in)", payload_in)

        # Payload for clock out
        payload_out = {'msnv': row['emp_code'], 'kihieumay': device_name, 'timestamp': timestamp_clockout}
        # except Exception as e:
        #     print(f"Exception on row {row['id']}: {e}")
        #     break


def process_new_records(data):
    """
    Process and filter new records based on date comparison
    """
    last_date = load_last_punch_time()
    print(f"Last processed date: {last_date}")

    new_records = []
    latest_date = None

    for record in data['data']:
        att_date = record['att_date']

        # compare day (string comparison works for YYYY-MM-DD format)
        if att_date >= last_date:
            # add record if clock_in is not None
            if record.get('clock_in') is not None:
                new_records.append(record)

            if latest_date is None or att_date > latest_date:
                latest_date = att_date

    # check vs file data
    if check_old_vs_current_records(new_records):
        return {"messages": "Not new records"}

    call_api(new_records)
    # update lastest day
    if latest_date:
        save_last_date(latest_date)

    # save new new_records
    save_last_record(new_records)
    print_result(new_records)
    # return new_records


def check_old_vs_current_records(new_records):
    last_records = load_last_record()
    if not last_records:
        return False
    return new_records == last_records


def print_result(new_records):
    print(f"\nFound {len(new_records)} new records:")
    for i, record in enumerate(new_records, 1):
        clock_in = record.get('clock_in') or 'None'
        clock_out = record.get('clock_out') or 'None'
        print(f"{i}. {record['emp_code']} - {record['att_date']} (IN: {clock_in}, OUT: {clock_out})")


data = {
    "count": 76,
    "next": "http://127.0.0.1:89/att/api/totalTimeCardReportV2/?areas=-1&departments=1&employees=-1&end_date=2025-08-03&groups=-1&page=2&page_size=20&start_date=2025-07-28",
    "previous": None,
    "msg": "",
    "code": 0,
    "data": [
        {
            "id": "517e1b1f-2ffa-4ace-875d-d5de3c986cfb",
            "emp_id": 33,
            "emp_code": "10",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": "09:06",
            "clock_out": "09:07",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "517e1b1f-2ffa-4ace-875d-d5de3c986cfb",
            "emp_id": 33,
            "emp_code": "10",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "14b1771d-d0d8-4057-906e-723c379e5ff9",
            "emp_id": 33,
            "emp_code": "10",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": "00:03",
            "clock_out": "00:04",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "816cc1c3-e744-4555-83c8-29815654fe6b",
            "emp_id": 17,
            "emp_code": "10001",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "5172ed53-6535-455b-98c5-c0d659d31997",
            "emp_id": 17,
            "emp_code": "10001",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "fbd3b8a4-a91d-491c-96b0-def692bb61a9",
            "emp_id": 16,
            "emp_code": "10002",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "f88b6db7-9936-4d50-93e7-21195980a955",
            "emp_id": 16,
            "emp_code": "10002",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "3aa45ef5-1dcf-43b5-a717-d28322e9d3ab",
            "emp_id": 32,
            "emp_code": "140010",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "b02f6d8f-c8ad-49fa-abdb-27b820438b07",
            "emp_id": 32,
            "emp_code": "140010",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "9ce34f9f-f017-492b-8242-f6c6fd6f1fc9",
            "emp_id": 8,
            "emp_code": "140011",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "08:59",
            "clock_out": "16:00",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "07:01",
            "worked_hrs": "07:01",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "7.0",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "837ba9bd-95e0-465d-99c2-fa337705ef65",
            "emp_id": 8,
            "emp_code": "140011",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "09:23",
            "clock_out": "19:07",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "09:44",
            "worked_hrs": "09:44",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "9.7",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "4d474968-8bf7-4058-b43f-3e94eece9c91",
            "emp_id": 14,
            "emp_code": "140012",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "11:28",
            "clock_out": "15:18",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "03:49",
            "worked_hrs": "03:49",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "3.8",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "cc718e61-f945-4169-9333-078df3e5e025",
            "emp_id": 14,
            "emp_code": "140012",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "10:30",
            "clock_out": "17:19",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "06:48",
            "worked_hrs": "06:48",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "6.8",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "25c6005f-2d35-4f07-b7c9-afa8bab405d3",
            "emp_id": 13,
            "emp_code": "140013",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "09:06",
            "clock_out": "18:05",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "08:58",
            "worked_hrs": "08:58",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "9.0",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "5789a663-c622-4076-98f4-75d64f8d3f4a",
            "emp_id": 13,
            "emp_code": "140013",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "09:13",
            "clock_out": "17:58",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "08:45",
            "worked_hrs": "08:45",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "8.8",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "c3134f6d-1114-461a-8cca-32db2d1bff8e",
            "emp_id": 18,
            "emp_code": "140014",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "0.0",
            "clock_in": None,
            "clock_out": None,
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "",
            "worked_hrs": "",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "42317152-d5db-4b25-8593-9ba50986c8b0",
            "emp_id": 18,
            "emp_code": "140014",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "08:53",
            "clock_out": "19:07",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "10:14",
            "worked_hrs": "10:14",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "10.2",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "bdf8b4a2-2c85-437b-abab-0998a8778f63",
            "emp_id": 21,
            "emp_code": "143018",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "10:32",
            "clock_out": "17:44",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "07:12",
            "worked_hrs": "07:12",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "7.2",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "d8977a57-6385-48af-ade6-b0b6517ef5ab",
            "emp_id": 21,
            "emp_code": "143018",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "10:22",
            "clock_out": "18:23",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "08:00",
            "worked_hrs": "08:00",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "8.0",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "910bbafc-8257-49d9-b4b7-cb514c5b105d",
            "emp_id": 22,
            "emp_code": "143019",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-28",
            "weekday": "Thứ hai",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "09:26",
            "clock_out": "17:03",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-28",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "07:36",
            "worked_hrs": "07:36",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "7.6",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        },
        {
            "id": "e80dd618-cf80-4fdc-96cd-3f2bc7da7654",
            "emp_id": 22,
            "emp_code": "143019",
            "first_name": "",
            "last_name": None,
            "nick_name": None,
            "gender": None,
            "company_code": "1",
            "company_name": "company.default",
            "dept_code": "1",
            "dept_name": "Phòng ban",
            "position_code": None,
            "position_name": None,
            "att_date": "2025-07-29",
            "weekday": "Thứ ba",
            "time_table_alias": "",
            "check_in": "00:00",
            "check_out": "00:00",
            "work_day": "1.0",
            "clock_in": "09:24",
            "clock_out": "17:38",
            "break_out": None,
            "break_in": None,
            "att_date_normal": "2025-07-29",
            "time_table_id": None,
            "full_attendance": 1,
            "duration": "12:00",
            "duty_duration": "",
            "total_hrs": "08:13",
            "worked_hrs": "08:13",
            "actual_worked": "",
            "break_duration": "",
            "break_total_hrs": "",
            "break_hrs": "",
            "actual_break": "",
            "approval_hrs": "",
            "early_in": "",
            "late_out": "",
            "unschedule": "",
            "remaining": "",
            "total_ot": "",
            "rule_total_ot": "",
            "total_leave": "",
            "paycode_1": "8.2",
            "paycode_2": "",
            "paycode_3": "",
            "paycode_4": "",
            "paycode_5": "",
            "paycode_6": "",
            "paycode_7": "",
            "paycode_8": "",
            "paycode_9": "",
            "paycode_10": "",
            "paycode_11": "",
            "paycode_12": "",
            "paycode_13": "",
            "paycode_14": "",
            "paycode_15": "",
            "paycode_16": "",
            "paycode_17": "",
            "paycode_18": ""
        }
    ]
}

print(process_new_records(data))
